export const CHART = "CHART";
export const CHART_SUCCESS = "CHART_SUCCESS";
export const CHART_FAILED = "CHART_FAILED";

export const POST_CHART = "POST_CHART";
export const POST_CHART_SUCCESS = "POST_CHART_SUCCESS";
export const POST_CHART_FAILED = "POST_CHART_FAILED";

export const UPDATE_CHART = "UPDATE_CHART";
export const UPDATE_CHART_SUCCESS = "UPDATE_CHART_SUCCESS";
export const UPDATE_CHART_FAILED = "UPDATE_CHART_FAILED";
